#!/bin/bash

PRJ_DIR=..
XSA_PKG=../../vivado-hdl-prjs/zuboard1cg/design_1_wrapper.xsa

xsct tcl/platform.tcl $PRJ_DIR $XSA_PKG

# Remove autogenerated files from Vitis
rm -rf $PRJ_DIR/.*
rm -rf $PRJ_DIR/*.log
rm -rf .*